const { Follow } = require("../models");

const followSeed = async () => {
    const followData = [
        { followingUserId: 1, followerUserId: 1 },
        { followingUserId: 2, followerUserId: 2 },
        { followingUserId: 3, followerUserId: 3 },
        { followingUserId: 4, followerUserId: 4 },
        { followingUserId: 5, followerUserId: 5 },
        { followingUserId: 6, followerUserId: 6 },
        { followingUserId: 7, followerUserId: 7 },
        { followingUserId: 8, followerUserId: 8 },
        { followingUserId: 9, followerUserId: 9 },
        { followingUserId: 10, followerUserId: 10 },
        { followingUserId: 11, followerUserId: 11 },
        { followingUserId: 12, followerUserId: 12 },
        { followingUserId: 13, followerUserId: 13 },
        { followingUserId: 14, followerUserId: 14 },
        { followingUserId: 15, followerUserId: 15 },
        { followingUserId: 16, followerUserId: 16 },
        { followingUserId: 17, followerUserId: 17 },
        { followingUserId: 18, followerUserId: 18 },
        { followingUserId: 19, followerUserId: 19 },
        { followingUserId: 20, followerUserId: 20 },
        { followingUserId: 21, followerUserId: 21 },
        { followingUserId: 22, followerUserId: 22 },
        { followingUserId: 23, followerUserId: 23 },
        { followingUserId: 24, followerUserId: 24 },
        { followingUserId: 25, followerUserId: 25 },
        { followingUserId: 26, followerUserId: 26 },
        { followingUserId: 27, followerUserId: 27 },
        { followingUserId: 28, followerUserId: 28 },
        { followingUserId: 29, followerUserId: 29 },
        { followingUserId: 30, followerUserId: 30 },
        { followingUserId: 31, followerUserId: 31 },
        { followingUserId: 32, followerUserId: 32 },
        { followingUserId: 33, followerUserId: 33 },
        { followingUserId: 34, followerUserId: 34 },
        { followingUserId: 35, followerUserId: 35 },
        { followingUserId: 36, followerUserId: 36 },
        { followingUserId: 37, followerUserId: 37 },
        { followingUserId: 38, followerUserId: 38 },
        { followingUserId: 39, followerUserId: 39 },
        { followingUserId: 40, followerUserId: 40 },
        { followingUserId: 41, followerUserId: 41 },
        { followingUserId: 42, followerUserId: 42 },
        { followingUserId: 43, followerUserId: 43 },
        { followingUserId: 44, followerUserId: 44 },
        { followingUserId: 45, followerUserId: 45 },
        { followingUserId: 46, followerUserId: 46 },
        { followingUserId: 47, followerUserId: 47 },
        { followingUserId: 48, followerUserId: 48 },
        { followingUserId: 49, followerUserId: 49 },
        { followingUserId: 50, followerUserId: 50 },
        // { followingUserId: 51, followerUserId: 51 },
        // { followingUserId: 52, followerUserId: 52 },
        // { followingUserId: 53, followerUserId: 53 },
        // { followingUserId: 54, followerUserId: 54 },
        // { followingUserId: 55, followerUserId: 55 },
        // { followingUserId: 56, followerUserId: 56 },
        // { followingUserId: 57, followerUserId: 57 },
        // { followingUserId: 58, followerUserId: 58 },
        // { followingUserId: 59, followerUserId: 59 },
        // { followingUserId: 60, followerUserId: 60 },
        // { followingUserId: 61, followerUserId: 61 },
        // { followingUserId: 62, followerUserId: 62 },
        // { followingUserId: 63, followerUserId: 63 },
        // { followingUserId: 64, followerUserId: 64 },
        // { followingUserId: 65, followerUserId: 65 },
        // { followingUserId: 66, followerUserId: 66 },
        // { followingUserId: 67, followerUserId: 67 },
        // { followingUserId: 68, followerUserId: 68 },
        // { followingUserId: 69, followerUserId: 69 },
        // { followingUserId: 70, followerUserId: 70 },
        // { followingUserId: 71, followerUserId: 71 },
        // { followingUserId: 72, followerUserId: 72 },
        // { followingUserId: 73, followerUserId: 73 },
        // { followingUserId: 74, followerUserId: 74 },
        // { followingUserId: 75, followerUserId: 75 },
        // { followingUserId: 76, followerUserId: 76 },
        // { followingUserId: 77, followerUserId: 77 },
        // { followingUserId: 78, followerUserId: 78 },
        // { followingUserId: 79, followerUserId: 79 },
        // { followingUserId: 80, followerUserId: 80 },
        // { followingUserId: 81, followerUserId: 81 },
        // { followingUserId: 82, followerUserId: 82 },
        // { followingUserId: 83, followerUserId: 83 },
        // { followingUserId: 84, followerUserId: 84 },
        // { followingUserId: 85, followerUserId: 85 },
        // { followingUserId: 86, followerUserId: 86 },
        // { followingUserId: 87, followerUserId: 87 },
        // { followingUserId: 88, followerUserId: 88 },
        // { followingUserId: 89, followerUserId: 89 },
        // { followingUserId: 90, followerUserId: 90 },
        // { followingUserId: 91, followerUserId: 91 },
        // { followingUserId: 92, followerUserId: 92 },
        // { followingUserId: 93, followerUserId: 93 },
        // { followingUserId: 94, followerUserId: 94 },
        // { followingUserId: 95, followerUserId: 95 },
        // { followingUserId: 96, followerUserId: 96 },
        // { followingUserId: 97, followerUserId: 97 },
        // { followingUserId: 98, followerUserId: 98 },
        // { followingUserId: 99, followerUserId: 99 },
        // { followingUserId: 100, followerUserId: 100 },
    ];

    let res = await Follow.bulkCreate(followData);
    // console.log(res);
    // process.exit(0);
};
// userSeed();

module.exports = followSeed;
