const { Like } = require("../models");

const userSeed = async () => {
    const likeData = [
        { postId: 1, userId: 1 },
        { postId: 1, userId: 2 },
        { postId: 1, userId: 3 },
        { postId: 2, userId: 2 },
        { postId: 2, userId: 3 },
        { postId: 2, userId: 4 },
        { postId: 3, userId: 3 },
        { postId: 3, userId: 6 },
        { postId: 3, userId: 7 },
        { postId: 4, userId: 4 },
        { postId: 5, userId: 5 },
        { postId: 6, userId: 6 },
        { postId: 7, userId: 7 },
        { postId: 8, userId: 8 },
        { postId: 9, userId: 9 },
        { postId: 10, userId: 10 },
        { postId: 11, userId: 11 },
        { postId: 12, userId: 12 },
        { postId: 13, userId: 13 },
        { postId: 14, userId: 14 },
        { postId: 15, userId: 15 },
        { postId: 16, userId: 16 },
        { postId: 17, userId: 17 },
        { postId: 18, userId: 18 },
        { postId: 19, userId: 19 },
        { postId: 20, userId: 20 },
        { postId: 21, userId: 21 },
        { postId: 22, userId: 22 },
        { postId: 23, userId: 23 },
        { postId: 24, userId: 24 },
        { postId: 25, userId: 25 },
        { postId: 26, userId: 26 },
        { postId: 27, userId: 27 },
        { postId: 28, userId: 28 },
        { postId: 29, userId: 29 },
        { postId: 30, userId: 30 },
        { postId: 31, userId: 31 },
        { postId: 32, userId: 32 },
        { postId: 33, userId: 33 },
        { postId: 34, userId: 34 },
        { postId: 35, userId: 35 },
        { postId: 36, userId: 36 },
        { postId: 37, userId: 37 },
        { postId: 38, userId: 38 },
        { postId: 39, userId: 39 },
        { postId: 40, userId: 40 },
        { postId: 41, userId: 41 },
        { postId: 42, userId: 42 },
        { postId: 43, userId: 43 },
        { postId: 44, userId: 44 },
        { postId: 45, userId: 45 },
        { postId: 46, userId: 46 },
        { postId: 47, userId: 47 },
        { postId: 48, userId: 48 },
        { postId: 49, userId: 49 },
        { postId: 50, userId: 50 },
        // { postId: 51, userId: 51 },
        // { postId: 52, userId: 52 },
        // { postId: 53, userId: 53 },
        // { postId: 54, userId: 54 },
        // { postId: 55, userId: 55 },
        // { postId: 56, userId: 56 },
        // { postId: 57, userId: 57 },
        // { postId: 58, userId: 58 },
        // { postId: 59, userId: 59 },
        // { postId: 60, userId: 60 },
        // { postId: 61, userId: 61 },
        // { postId: 62, userId: 62 },
        // { postId: 63, userId: 63 },
        // { postId: 64, userId: 64 },
        // { postId: 65, userId: 65 },
        // { postId: 66, userId: 66 },
        // { postId: 67, userId: 67 },
        // { postId: 68, userId: 68 },
        // { postId: 69, userId: 69 },
        // { postId: 70, userId: 70 },
        { replyId: 1, userId: 1 },
        { replyId: 1, userId: 2 },
        { replyId: 1, userId: 3 },
        { replyId: 2, userId: 3 },
        { replyId: 2, userId: 6 },
        { replyId: 3, userId: 7 },
        { replyId: 3, userId: 8 },
        { replyId: 3, userId: 2 },
        { replyId: 4, userId: 20 },
        { replyId: 4, userId: 32 },
        { replyId: 5, userId: 31 },
    ];

    await Like.bulkCreate(likeData);
};
module.exports = userSeed;
