const { Tag } = require("../models");

const userSeed = async () => {
    const TagData = [
        { tagName: "nunc vestibulum ante", tagCount: 1 },
        { tagName: "pellentesque viverra", tagCount: 2 },
        { tagName: "habitasse platea", tagCount: 3 },
        { tagName: "ante ipsum", tagCount: 4 },
        { tagName: "consectetuer eget rutrum", tagCount: 5 },
        { tagName: "magna vestibulum aliquet", tagCount: 6 },
        { tagName: "orci vehicula", tagCount: 7 },
        { tagName: "et tempus", tagCount: 8 },
        { tagName: "a pede kaka", tagCount: 9 },
        { tagName: "magna bibendum", tagCount: 10 },
        { tagName: "dolor", tagCount: 11 },
        { tagName: "nulla eget eros", tagCount: 12 },
        { tagName: "iaculis justo in", tagCount: 13 },
        { tagName: "praesent blandit nam", tagCount: 14 },
        { tagName: "maecenas pulvinar", tagCount: 15 },
        { tagName: "ut massa", tagCount: 16 },
        { tagName: "adipisqwe", tagCount: 17 },
        { tagName: "blandit mi in", tagCount: 18 },
        { tagName: "nascetur ridiculus", tagCount: 19 },
        { tagName: "nonummy integer non", tagCount: 20 },
        { tagName: "aenean lectus", tagCount: 21 },
        { tagName: "ac nulla sed", tagCount: 22 },
        { tagName: "in", tagCount: 23 },
        { tagName: "ut massala", tagCount: 24 },
        { tagName: "vestibulum ante", tagCount: 25 },
        { tagName: "nulla tempus", tagCount: 26 },
        { tagName: "turpis eget", tagCount: 27 },
        { tagName: "convallis eget", tagCount: 28 },
        { tagName: "nibh ligula", tagCount: 29 },
        { tagName: "imperdiet", tagCount: 30 },
        { tagName: "non ligula pellentesque", tagCount: 31 },
        { tagName: "laoreet", tagCount: 32 },
        { tagName: "pretium iaculis justo", tagCount: 33 },
        { tagName: "mauris lacinia", tagCount: 34 },
        { tagName: "pellentesque", tagCount: 35 },
        { tagName: "quis", tagCount: 36 },
        { tagName: "nisl", tagCount: 37 },
        { tagName: "diam cras pellentesque", tagCount: 38 },
        { tagName: "tristique fusce congue", tagCount: 39 },
        { tagName: "proin at", tagCount: 40 },
        { tagName: "vel lectus in", tagCount: 41 },
        { tagName: "nulla nunc purus", tagCount: 42 },
        { tagName: "id", tagCount: 43 },
        { tagName: "semper est", tagCount: 44 },
        { tagName: "adipis molestie", tagCount: 45 },
        { tagName: "augue luctus", tagCount: 46 },
        { tagName: "vestibulum ac est", tagCount: 47 },
        { tagName: "sapien dignissim", tagCount: 48 },
        { tagName: "feugiat", tagCount: 49 },
        { tagName: "cursus urna ut", tagCount: 50 },
        { tagName: "tempus vikaka", tagCount: 51 },
        { tagName: "orci luctus", tagCount: 52 },
        { tagName: "adipiscing", tagCount: 53 },
        { tagName: "aenean auctor", tagCount: 54 },
        { tagName: "ut", tagCount: 55 },
        { tagName: "pede justo", tagCount: 56 },
        { tagName: "hac habitasse platea", tagCount: 57 },
        { tagName: "sapien sapien non", tagCount: 58 },
        { tagName: "mauris non", tagCount: 59 },
        { tagName: "in faucibus orci", tagCount: 60 },
        { tagName: "ultricies", tagCount: 61 },
        { tagName: "sit amet diam", tagCount: 62 },
        { tagName: "id nulla", tagCount: 63 },
        { tagName: "donec quis", tagCount: 64 },
        { tagName: "nunc donec quis", tagCount: 65 },
        { tagName: "odio", tagCount: 66 },
        { tagName: "id justo sit", tagCount: 67 },
        { tagName: "sit amet", tagCount: 68 },
        { tagName: "eget", tagCount: 69 },
        { tagName: "nec", tagCount: 70 },
        { tagName: "vivamus", tagCount: 71 },
        { tagName: "faucibus orci", tagCount: 72 },
        { tagName: "morbi", tagCount: 73 },
        { tagName: "eget eleifend luctus", tagCount: 74 },
        { tagName: "turpis a pede", tagCount: 75 },
        { tagName: "sed tristique in", tagCount: 76 },
        { tagName: "integer", tagCount: 77 },
        { tagName: "vivacha", tagCount: 78 },
        { tagName: "non sodales sed", tagCount: 79 },
        { tagName: "at dolor", tagCount: 80 },
    ];

    let res = await Tag.bulkCreate(TagData);
    // console.log(res);
    // process.exit(0);
};
// userSeed();

module.exports = userSeed;
