const { User } = require("../models");
require("dotenv").config();
const bcryptService = require("../services/bcryptService");

const userSeed = async () => {
    const userData = [
        {
            id: 1,
            username: "nchristofe0",
            firstName: "Northrup",
            lastName: "Christofe",
            email: "nchristofe0@yahoo.com",
            profileImageUrl: "http://dummyimage.com/133x100.png/cc0000/ffffff",
        },
        {
            id: 2,
            username: "aparades1",
            firstName: "Aldridge",
            lastName: "Parades",
            email: "aparades1@mit.edu",
            profileImageUrl: "http://dummyimage.com/232x100.png/5fa2dd/ffffff",
        },
        {
            id: 3,
            username: "bharm2",
            firstName: "Ber",
            lastName: "Harm",
            email: "bharm2@twitpic.com",
            profileImageUrl: "http://dummyimage.com/131x100.png/dddddd/000000",
        },
        {
            id: 4,
            username: "cyacob3",
            firstName: "Chrystel",
            lastName: "Yacob",
            email: "cyacob3@yellowpages.com",
            profileImageUrl: "http://dummyimage.com/137x100.png/dddddd/000000",
        },
        {
            id: 5,
            username: "jrosenblad4",
            firstName: "Jud",
            lastName: "Rosenblad",
            email: "jrosenblad4@kickstarter.com",
            profileImageUrl: "http://dummyimage.com/185x100.png/5fa2dd/ffffff",
        },
        {
            id: 6,
            username: "mdomanski5",
            firstName: "Marguerite",
            lastName: "Domanski",
            email: "mdomanski5@scientificamerican.com",
            profileImageUrl: "http://dummyimage.com/213x100.png/cc0000/ffffff",
        },
        {
            id: 7,
            username: "kbiggen6",
            firstName: "Kassie",
            lastName: "Biggen",
            email: "kbiggen6@privacy.gov.au",
            profileImageUrl: "http://dummyimage.com/245x100.png/dddddd/000000",
        },
        {
            id: 8,
            username: "tpawelczyk7",
            firstName: "Trey",
            lastName: "Pawelczyk",
            email: "tpawelczyk7@linkedin.com",
            profileImageUrl: "http://dummyimage.com/249x100.png/5fa2dd/ffffff",
        },
        {
            id: 9,
            username: "jwillden8",
            firstName: "Julissa",
            lastName: "Willden",
            email: "jwillden8@cam.ac.uk",
            profileImageUrl: "http://dummyimage.com/134x100.png/dddddd/000000",
        },
        {
            id: 10,
            username: "mbladon9",
            firstName: "Maryrose",
            lastName: "Bladon",
            email: "mbladon9@china.com.cn",
            profileImageUrl: "http://dummyimage.com/196x100.png/cc0000/ffffff",
        },
        {
            id: 11,
            username: "zgodwina",
            firstName: "Zach",
            lastName: "Godwin",
            email: "zgodwina@google.co.jp",
            profileImageUrl: "http://dummyimage.com/118x100.png/dddddd/000000",
        },
        {
            id: 12,
            username: "clangwadeb",
            firstName: "Chloris",
            lastName: "Langwade",
            email: "clangwadeb@google.com.au",
            profileImageUrl: "http://dummyimage.com/110x100.png/dddddd/000000",
        },
        {
            id: 13,
            username: "dnizetc",
            firstName: "Dilly",
            lastName: "Nizet",
            email: "dnizetc@boston.com",
            profileImageUrl: "http://dummyimage.com/156x100.png/dddddd/000000",
        },
        {
            id: 14,
            username: "fmowend",
            firstName: "Fiona",
            lastName: "Mowen",
            email: "fmowend@linkedin.com",
            profileImageUrl: "http://dummyimage.com/228x100.png/ff4444/ffffff",
        },
        {
            id: 15,
            username: "ktrodlere",
            firstName: "Kiah",
            lastName: "Trodler",
            email: "ktrodlere@myspace.com",
            profileImageUrl: "http://dummyimage.com/100x100.png/dddddd/000000",
        },
        {
            id: 16,
            username: "dbolerf",
            firstName: "Davon",
            lastName: "Boler",
            email: "dbolerf@ucsd.edu",
            profileImageUrl: "http://dummyimage.com/147x100.png/ff4444/ffffff",
        },
        {
            id: 17,
            username: "dsquireg",
            firstName: "Dieter",
            lastName: "Squire",
            email: "dsquireg@cocolog-nifty.com",
            profileImageUrl: "http://dummyimage.com/124x100.png/dddddd/000000",
        },
        {
            id: 18,
            username: "bnewcombeh",
            firstName: "Bartolemo",
            lastName: "Newcombe",
            email: "bnewcombeh@google.cn",
            profileImageUrl: "http://dummyimage.com/106x100.png/cc0000/ffffff",
        },
        {
            id: 19,
            username: "ljewelli",
            firstName: "L;urette",
            lastName: "Jewell",
            email: "ljewelli@comsenz.com",
            profileImageUrl: "http://dummyimage.com/149x100.png/ff4444/ffffff",
        },
        {
            id: 20,
            username: "paschej",
            firstName: "Page",
            lastName: "Asche",
            email: "paschej@mapy.cz",
            profileImageUrl: "http://dummyimage.com/234x100.png/cc0000/ffffff",
        },
        {
            id: 21,
            username: "lgunningk",
            firstName: "Laurel",
            lastName: "Gunning",
            email: "lgunningk@marketwatch.com",
            profileImageUrl: "http://dummyimage.com/133x100.png/cc0000/ffffff",
        },
        {
            id: 22,
            username: "tkingslyl",
            firstName: "Thornton",
            lastName: "Kingsly",
            email: "tkingslyl@latimes.com",
            profileImageUrl: "http://dummyimage.com/155x100.png/dddddd/000000",
        },
        {
            id: 23,
            username: "bgeddism",
            firstName: "Bernarr",
            lastName: "Geddis",
            email: "bgeddism@bloglovin.com",
            profileImageUrl: "http://dummyimage.com/169x100.png/dddddd/000000",
        },
        {
            id: 24,
            username: "oohartnedyn",
            firstName: "Ora",
            lastName: "O'Hartnedy",
            email: "oohartnedyn@51.la",
            profileImageUrl: "http://dummyimage.com/250x100.png/5fa2dd/ffffff",
        },
        {
            id: 25,
            username: "ddodridgeo",
            firstName: "Dewitt",
            lastName: "Dodridge",
            email: "ddodridgeo@tmall.com",
            profileImageUrl: "http://dummyimage.com/215x100.png/cc0000/ffffff",
        },
        {
            id: 26,
            username: "mmartschikp",
            firstName: "Mariann",
            lastName: "Martschik",
            email: "mmartschikp@360.cn",
            profileImageUrl: "http://dummyimage.com/116x100.png/5fa2dd/ffffff",
        },
        {
            id: 27,
            username: "bpumphreyq",
            firstName: "Babb",
            lastName: "Pumphrey",
            email: "bpumphreyq@japanpost.jp",
            profileImageUrl: "http://dummyimage.com/206x100.png/ff4444/ffffff",
        },
        {
            id: 28,
            username: "lphiferr",
            firstName: "Lynette",
            lastName: "Phifer",
            email: "lphiferr@goodreads.com",
            profileImageUrl: "http://dummyimage.com/100x100.png/cc0000/ffffff",
        },
        {
            id: 29,
            username: "smartills",
            firstName: "Saundra",
            lastName: "Martill",
            email: "smartills@zdnet.com",
            profileImageUrl: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
        },
        {
            id: 30,
            username: "pcrewst",
            firstName: "Papagena",
            lastName: "Crews",
            email: "pcrewst@virginia.edu",
            profileImageUrl: "http://dummyimage.com/132x100.png/dddddd/000000",
        },
        {
            id: 31,
            username: "ecaswillu",
            firstName: "Elka",
            lastName: "Caswill",
            email: "ecaswillu@gmpg.org",
            profileImageUrl: "http://dummyimage.com/166x100.png/ff4444/ffffff",
        },
        {
            id: 32,
            username: "cdaelv",
            firstName: "Cecilla",
            lastName: "Dael",
            email: "cdaelv@tiny.cc",
            profileImageUrl: "http://dummyimage.com/190x100.png/dddddd/000000",
        },
        {
            id: 33,
            username: "ldesouzaw",
            firstName: "Lulu",
            lastName: "Desouza",
            email: "ldesouzaw@istockphoto.com",
            profileImageUrl: "http://dummyimage.com/191x100.png/dddddd/000000",
        },
        {
            id: 34,
            username: "schapierx",
            firstName: "Shepperd",
            lastName: "Chapier",
            email: "schapierx@umn.edu",
            profileImageUrl: "http://dummyimage.com/137x100.png/5fa2dd/ffffff",
        },
        {
            id: 35,
            username: "ktryey",
            firstName: "Karna",
            lastName: "Trye",
            email: "ktryey@comcast.net",
            profileImageUrl: "http://dummyimage.com/136x100.png/5fa2dd/ffffff",
        },
        {
            id: 36,
            username: "cchristofolz",
            firstName: "Cleveland",
            lastName: "Christofol",
            email: "cchristofolz@google.co.jp",
            profileImageUrl: "http://dummyimage.com/179x100.png/cc0000/ffffff",
        },
        {
            id: 37,
            username: "gchatain10",
            firstName: "Genvieve",
            lastName: "Chatain",
            email: "gchatain10@abc.net.au",
            profileImageUrl: "http://dummyimage.com/235x100.png/dddddd/000000",
        },
        {
            id: 38,
            username: "blynds11",
            firstName: "Brendis",
            lastName: "Lynds",
            email: "blynds11@usatoday.com",
            profileImageUrl: "http://dummyimage.com/104x100.png/dddddd/000000",
        },
        {
            id: 39,
            username: "jdrakard12",
            firstName: "Jimmy",
            lastName: "Drakard",
            email: "jdrakard12@howstuffworks.com",
            profileImageUrl: "http://dummyimage.com/189x100.png/5fa2dd/ffffff",
        },
        {
            id: 40,
            username: "lkoschke13",
            firstName: "Lawrence",
            lastName: "Koschke",
            email: "lkoschke13@wikia.com",
            profileImageUrl: "http://dummyimage.com/171x100.png/5fa2dd/ffffff",
        },
        {
            id: 41,
            username: "asimonich14",
            firstName: "Aleece",
            lastName: "Simonich",
            email: "asimonich14@desdev.cn",
            profileImageUrl: "http://dummyimage.com/230x100.png/cc0000/ffffff",
        },
        {
            id: 42,
            username: "fbemment15",
            firstName: "Fidel",
            lastName: "Bemment",
            email: "fbemment15@cbc.ca",
            profileImageUrl: "http://dummyimage.com/116x100.png/cc0000/ffffff",
        },
        {
            id: 43,
            username: "smaccaughey16",
            firstName: "Suzy",
            lastName: "MacCaughey",
            email: "smaccaughey16@wordpress.com",
            profileImageUrl: "http://dummyimage.com/216x100.png/dddddd/000000",
        },
        {
            id: 44,
            username: "knutman17",
            firstName: "Kaile",
            lastName: "Nutman",
            email: "knutman17@wordpress.com",
            profileImageUrl: "http://dummyimage.com/149x100.png/dddddd/000000",
        },
        {
            id: 45,
            username: "wstanford18",
            firstName: "Wylie",
            lastName: "Stanford",
            email: "wstanford18@techcrunch.com",
            profileImageUrl: "http://dummyimage.com/139x100.png/5fa2dd/ffffff",
        },
        {
            id: 46,
            username: "afines19",
            firstName: "Anstice",
            lastName: "Fines",
            email: "afines19@barnesandnoble.com",
            profileImageUrl: "http://dummyimage.com/217x100.png/ff4444/ffffff",
        },
        {
            id: 47,
            username: "aodee1a",
            firstName: "Ardis",
            lastName: "O'Dee",
            email: "aodee1a@tripod.com",
            profileImageUrl: "http://dummyimage.com/174x100.png/ff4444/ffffff",
        },
        {
            id: 48,
            username: "asherred1b",
            firstName: "Armando",
            lastName: "Sherred",
            email: "asherred1b@telegraph.co.uk",
            profileImageUrl: "http://dummyimage.com/131x100.png/5fa2dd/ffffff",
        },
        {
            id: 49,
            username: "hgoodsir1c",
            firstName: "Haskell",
            lastName: "Goodsir",
            email: "hgoodsir1c@dmoz.org",
            profileImageUrl: "http://dummyimage.com/105x100.png/cc0000/ffffff",
        },
        {
            id: 50,
            username: "cmcmurdo1d",
            firstName: "Charlotta",
            lastName: "McMurdo",
            email: "cmcmurdo1d@netscape.com",
            profileImageUrl: "http://dummyimage.com/137x100.png/ff4444/ffffff",
        },
        // {
        //     id: 51,
        //     username: "sworman1e",
        //     firstName: "Sherwin",
        //     lastName: "Worman",
        //     email: "sworman1e@clickbank.net",
        //     profileImageUrl: "http://dummyimage.com/233x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 52,
        //     username: "clecount1f",
        //     firstName: "Carroll",
        //     lastName: "Le - Count",
        //     email: "clecount1f@wix.com",
        //     profileImageUrl: "http://dummyimage.com/141x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 53,
        //     username: "kmundow1g",
        //     firstName: "Keir",
        //     lastName: "Mundow",
        //     email: "kmundow1g@apache.org",
        //     profileImageUrl: "http://dummyimage.com/142x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 54,
        //     username: "gthunderchief1h",
        //     firstName: "Gwenny",
        //     lastName: "Thunderchief",
        //     email: "gthunderchief1h@themeforest.net",
        //     profileImageUrl: "http://dummyimage.com/245x100.png/cc0000/ffffff",
        // },
        // {
        //     id: 55,
        //     username: "dmckim1i",
        //     firstName: "Dud",
        //     lastName: "McKim",
        //     email: "dmckim1i@ustream.tv",
        //     profileImageUrl: "http://dummyimage.com/156x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 56,
        //     username: "sgilbee1j",
        //     firstName: "Shell",
        //     lastName: "Gilbee",
        //     email: "sgilbee1j@cmu.edu",
        //     profileImageUrl: "http://dummyimage.com/105x100.png/cc0000/ffffff",
        // },
        // {
        //     id: 57,
        //     username: "lbabbage1k",
        //     firstName: "Liva",
        //     lastName: "Babbage",
        //     email: "lbabbage1k@elegantthemes.com",
        //     profileImageUrl: "http://dummyimage.com/232x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 58,
        //     username: "phammersley1l",
        //     firstName: "Petronille",
        //     lastName: "Hammersley",
        //     email: "phammersley1l@boston.com",
        //     profileImageUrl: "http://dummyimage.com/181x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 59,
        //     username: "rboldry1m",
        //     firstName: "Robbyn",
        //     lastName: "Boldry",
        //     email: "rboldry1m@google.fr",
        //     profileImageUrl: "http://dummyimage.com/221x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 60,
        //     username: "ykyrkeman1n",
        //     firstName: "Yul",
        //     lastName: "Kyrkeman",
        //     email: "ykyrkeman1n@reverbnation.com",
        //     profileImageUrl: "http://dummyimage.com/121x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 61,
        //     username: "lchaters1o",
        //     firstName: "Lyda",
        //     lastName: "Chaters",
        //     email: "lchaters1o@hatena.ne.jp",
        //     profileImageUrl: "http://dummyimage.com/120x100.png/dddddd/000000",
        // },
        // {
        //     id: 62,
        //     username: "gladewig1p",
        //     firstName: "Gerty",
        //     lastName: "Ladewig",
        //     email: "gladewig1p@wordpress.com",
        //     profileImageUrl: "http://dummyimage.com/213x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 63,
        //     username: "lgrimbleby1q",
        //     firstName: "Laughton",
        //     lastName: "Grimbleby",
        //     email: "lgrimbleby1q@behance.net",
        //     profileImageUrl: "http://dummyimage.com/201x100.png/cc0000/ffffff",
        // },
        // {
        //     id: 64,
        //     username: "mlamperti1r",
        //     firstName: "Maryann",
        //     lastName: "Lamperti",
        //     email: "mlamperti1r@zimbio.com",
        //     profileImageUrl: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        // },
        // {
        //     id: 65,
        //     username: "hmacgorrie1s",
        //     firstName: "Hendrick",
        //     lastName: "MacGorrie",
        //     email: "hmacgorrie1s@google.it",
        //     profileImageUrl: "http://dummyimage.com/221x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 66,
        //     username: "whatley1t",
        //     firstName: "Wilhelm",
        //     lastName: "Hatley",
        //     email: "whatley1t@ucoz.ru",
        //     profileImageUrl: "http://dummyimage.com/195x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 67,
        //     username: "hfernley1u",
        //     firstName: "Hilton",
        //     lastName: "Fernley",
        //     email: "hfernley1u@icio.us",
        //     profileImageUrl: "http://dummyimage.com/196x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 68,
        //     username: "pkirvell1v",
        //     firstName: "Paul",
        //     lastName: "Kirvell",
        //     email: "pkirvell1v@stumbleupon.com",
        //     profileImageUrl: "http://dummyimage.com/146x100.png/dddddd/000000",
        // },
        // {
        //     id: 69,
        //     username: "missacof1w",
        //     firstName: "Merna",
        //     lastName: "Issacof",
        //     email: "missacof1w@cmu.edu",
        //     profileImageUrl: "http://dummyimage.com/131x100.png/dddddd/000000",
        // },
        // {
        //     id: 70,
        //     username: "ochinnick1x",
        //     firstName: "Oby",
        //     lastName: "Chinnick",
        //     email: "ochinnick1x@360.cn",
        //     profileImageUrl: "http://dummyimage.com/172x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 71,
        //     username: "kjanuszkiewicz1y",
        //     firstName: "Kris",
        //     lastName: "Januszkiewicz",
        //     email: "kjanuszkiewicz1y@miibeian.gov.cn",
        //     profileImageUrl: "http://dummyimage.com/173x100.png/dddddd/000000",
        // },
        // {
        //     id: 72,
        //     username: "fyandle1z",
        //     firstName: "Farr",
        //     lastName: "Yandle",
        //     email: "fyandle1z@state.tx.us",
        //     profileImageUrl: "http://dummyimage.com/179x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 73,
        //     username: "smintram20",
        //     firstName: "Shell",
        //     lastName: "Mintram",
        //     email: "smintram20@berkeley.edu",
        //     profileImageUrl: "http://dummyimage.com/211x100.png/dddddd/000000",
        // },
        // {
        //     id: 74,
        //     username: "kdayment21",
        //     firstName: "Katrina",
        //     lastName: "Dayment",
        //     email: "kdayment21@unesco.org",
        //     profileImageUrl: "http://dummyimage.com/144x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 75,
        //     username: "csharple22",
        //     firstName: "Claudine",
        //     lastName: "Sharple",
        //     email: "csharple22@mozilla.com",
        //     profileImageUrl: "http://dummyimage.com/129x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 76,
        //     username: "kpurbrick23",
        //     firstName: "Kellen",
        //     lastName: "Purbrick",
        //     email: "kpurbrick23@patch.com",
        //     profileImageUrl: "http://dummyimage.com/113x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 77,
        //     username: "afenelow24",
        //     firstName: "Ailyn",
        //     lastName: "Fenelow",
        //     email: "afenelow24@latimes.com",
        //     profileImageUrl: "http://dummyimage.com/145x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 78,
        //     username: "ssherringham25",
        //     firstName: "Sheree",
        //     lastName: "Sherringham",
        //     email: "ssherringham25@mozilla.org",
        //     profileImageUrl: "http://dummyimage.com/124x100.png/dddddd/000000",
        // },
        // {
        //     id: 79,
        //     username: "lcarlisi26",
        //     firstName: "Lewie",
        //     lastName: "Carlisi",
        //     email: "lcarlisi26@biblegateway.com",
        //     profileImageUrl: "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 80,
        //     username: "caiers27",
        //     firstName: "Chastity",
        //     lastName: "Aiers",
        //     email: "caiers27@mail.ru",
        //     profileImageUrl: "http://dummyimage.com/228x100.png/dddddd/000000",
        // },
        // {
        //     id: 81,
        //     username: "jscroggs28",
        //     firstName: "Jaquelin",
        //     lastName: "Scroggs",
        //     email: "jscroggs28@cmu.edu",
        //     profileImageUrl: "http://dummyimage.com/215x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 82,
        //     username: "pbeange29",
        //     firstName: "Patricio",
        //     lastName: "Beange",
        //     email: "pbeange29@de.vu",
        //     profileImageUrl: "http://dummyimage.com/147x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 83,
        //     username: "cbrownrigg2a",
        //     firstName: "Cindra",
        //     lastName: "Brownrigg",
        //     email: "cbrownrigg2a@cargocollective.com",
        //     profileImageUrl: "http://dummyimage.com/226x100.png/cc0000/ffffff",
        // },
        // {
        //     id: 84,
        //     username: "kfullard2b",
        //     firstName: "Kalila",
        //     lastName: "Fullard",
        //     email: "kfullard2b@walmart.com",
        //     profileImageUrl: "http://dummyimage.com/208x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 85,
        //     username: "frosborough2c",
        //     firstName: "Fan",
        //     lastName: "Rosborough",
        //     email: "frosborough2c@symantec.com",
        //     profileImageUrl: "http://dummyimage.com/228x100.png/dddddd/000000",
        // },
        // {
        //     id: 86,
        //     username: "wgravenor2d",
        //     firstName: "Wells",
        //     lastName: "Gravenor",
        //     email: "wgravenor2d@artisteer.com",
        //     profileImageUrl: "http://dummyimage.com/107x100.png/cc0000/ffffff",
        // },
        // {
        //     id: 87,
        //     username: "tcapron2e",
        //     firstName: "Trent",
        //     lastName: "Capron",
        //     email: "tcapron2e@businessinsider.com",
        //     profileImageUrl: "http://dummyimage.com/219x100.png/cc0000/ffffff",
        // },
        // {
        //     id: 88,
        //     username: "awooddisse2f",
        //     firstName: "Aurelea",
        //     lastName: "Wooddisse",
        //     email: "awooddisse2f@boston.com",
        //     profileImageUrl: "http://dummyimage.com/221x100.png/dddddd/000000",
        // },
        // {
        //     id: 89,
        //     username: "kdelicate2g",
        //     firstName: "Kelsy",
        //     lastName: "Delicate",
        //     email: "kdelicate2g@squarespace.com",
        //     profileImageUrl: "http://dummyimage.com/106x100.png/cc0000/ffffff",
        // },
        // {
        //     id: 90,
        //     username: "babdie2h",
        //     firstName: "Blisse",
        //     lastName: "Abdie",
        //     email: "babdie2h@google.pl",
        //     profileImageUrl: "http://dummyimage.com/195x100.png/dddddd/000000",
        // },
        // {
        //     id: 91,
        //     username: "ngillanders2i",
        //     firstName: "Nester",
        //     lastName: "Gillanders",
        //     email: "ngillanders2i@meetup.com",
        //     profileImageUrl: "http://dummyimage.com/219x100.png/cc0000/ffffff",
        // },
        // {
        //     id: 92,
        //     username: "rhubbold2j",
        //     firstName: "Reggie",
        //     lastName: "Hubbold",
        //     email: "rhubbold2j@bravesites.com",
        //     profileImageUrl: "http://dummyimage.com/108x100.png/5fa2dd/ffffff",
        // },
        // {
        //     id: 93,
        //     username: "wtattam2k",
        //     firstName: "Wallache",
        //     lastName: "Tattam",
        //     email: "wtattam2k@hostgator.com",
        //     profileImageUrl: "http://dummyimage.com/184x100.png/dddddd/000000",
        // },
        // {
        //     id: 94,
        //     username: "mrennison2l",
        //     firstName: "Merry",
        //     lastName: "Rennison",
        //     email: "mrennison2l@yahoo.co.jp",
        //     profileImageUrl: "http://dummyimage.com/188x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 95,
        //     username: "slarking2m",
        //     firstName: "Siegfried",
        //     lastName: "Larking",
        //     email: "slarking2m@scientificamerican.com",
        //     profileImageUrl: "http://dummyimage.com/171x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 96,
        //     username: "smclarens2n",
        //     firstName: "Sada",
        //     lastName: "McLarens",
        //     email: "smclarens2n@archive.org",
        //     profileImageUrl: "http://dummyimage.com/184x100.png/dddddd/000000",
        // },
        // {
        //     id: 97,
        //     username: "rjaggers2o",
        //     firstName: "Roy",
        //     lastName: "Jaggers",
        //     email: "rjaggers2o@howstuffworks.com",
        //     profileImageUrl: "http://dummyimage.com/169x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 98,
        //     username: "amcrinn2p",
        //     firstName: "Arnie",
        //     lastName: "McRinn",
        //     email: "amcrinn2p@gizmodo.com",
        //     profileImageUrl: "http://dummyimage.com/130x100.png/cc0000/ffffff",
        // },
        // {
        //     id: 99,
        //     username: "mmichurin2q",
        //     firstName: "Maury",
        //     lastName: "Michurin",
        //     email: "mmichurin2q@rambler.ru",
        //     profileImageUrl: "http://dummyimage.com/168x100.png/ff4444/ffffff",
        // },
        // {
        //     id: 100,
        //     username: "ateacy2r",
        //     firstName: "Arvin",
        //     lastName: "Teacy",
        //     email: "ateacy2r@theguardian.com",
        //     profileImageUrl: "http://dummyimage.com/161x100.png/ff4444/ffffff",
        // },
    ];

    const addPassword = async (user) => {
        const hashPassword = await bcryptService.hash(
            "12345678",
            process.env.HASH_SALT
        );
        return { ...user, password: hashPassword };
    };

    let newUserDataPromise = userData.map(async (user) => {
        return addPassword(user);
    });

    const newUserData = await Promise.all(newUserDataPromise);

    let res = await User.bulkCreate(newUserData);
    // console.log(res);
    // process.exit(0);
};
// userSeed();

module.exports = userSeed;
